name: micasa
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  flutter_launcher_icons: ^0.8.1
  beacon_broadcast: ^0.2.2
  uuid: ^2.2.2
  flutter_login: ^1.0.14
  cloud_firestore: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - 'lib/assets/'


flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/icon.png'
